### ISSUE TITLE
[Bug] Disabling notifications breaks entire My Profile menu

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/admin-ui-classic-bundle#935]
Changing from
```yaml
pimcore_admin:
    notifications:
        enabled: true
```
![Image](https://github.com/user-attachments/assets/c2892ba3-45e4-4b75-9ddf-24cc3fa01d03)

To:
```yaml
pimcore_admin:
    notifications:
        enabled: false
```
Which breaks the UI in ways that makes menu items such as *My Profile* and *Logout* unreachable.

![Image](https://github.com/user-attachments/assets/45f5792e-6230-4074-8f52-6b1a04bc82a5)
